from enum import Enum

class tipo_gasto(Enum):
    TRANSPORTE = 'TRANSPORTE'
    ALIMENTACION = 'ALIMENTACION'
    ALOJAMIENTO = 'ALOJAMIENTO'
    ENTRETENIMIENTO = 'ENTRETENIMIENTO'
    COMPRAS = 'COMPRAS'